### ISSUE TITLE
Install Wordpress into its own directory

### ISSUE THREAD

**Issue by andrew8er** [moritzjacobs/wordpress-boilerplate#1]
It would be beneficial to install Wordpress into its own (sub)directory.

Pros:
* The working tree of this project remains clean
* This project can be split up into multiple files (styles, classes, template files)
* The resulting Wordpress installation is clean, no files need to be deleted

Cons:
* The resulting Wordpress installation needs to be moved or the server config needs to be updated to the new web root

**Comment by moritzjacobs** [comment]
This is already the case. As you can see on the installer screen under "Core dir name" you can choose the directory's name. Whether you want to ignore the core dir in your CVS or not is your decision. See also the `wp-config-sample.php`.
