### ISSUE TITLE
Strict standards warning from `wpnp-sanitize-upload.php`

### ISSUE THREAD

**Issue by moritzjacobs** [moritzjacobs/wordpress-boilerplate#4]
`
Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method NPWP_Sanitize_uploads::sanitize_filename_on_upload() should not be called statically in /Users/mo/Dropbox/LAB/htdocs/wp-testbox/core/wp-includes/class-wp-hook.php on line 300
`

**Comment by manuelpiepereit** [comment]
fixed.
